Probando el manejo de errores con python